# SPDX-FileCopyrightText: 2023 James R. Barlow
# SPDX-License-Identifier: MPL-2.0

cirrus_linux_arm64_wheel_task:
  name: "linux arm64 Cirrus"
  alias: wheel_linux_arm
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 4
    memory: 4G

  env:
    CIBW_BUILD: >-
      cp38-manylinux_aarch64
      cp39-manylinux_aarch64
      cp310-manylinux_aarch64
      cp311-manylinux_aarch64
      cp312-manylinux_aarch64
      cp39-musllinux_aarch64
      cp310-musllinux_aarch64
      cp311-musllinux_aarch64
      cp312-musllinux_aarch64

  cibuildwheel_script:
    - apt-get install -y python3 python-is-python3 pipx
    - pipx run --python /usr/bin/python3 --spec cibuildwheel==2.20.0 cibuildwheel

  wheels_artifacts:
    path: "wheelhouse/*"
