version = 1
SPDX-PackageName = "pikepdf"
SPDX-PackageSupplier = "James R. Barlow <james@purplerock.ca>"
SPDX-PackageDownloadLocation = "https://github.com/pikepdf/pikepdf"

[[annotations]]
path = "licenses-for-wheels.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2022 James R. Barlow"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
    ".git_archival.txt",
    "REUSE.toml",
    "docs/**.csv",
    "docs/**.ipynb",
    "docs/**.py",
    "docs/**.rst",
    "docs/images/acrobat-attachments.png",
    "docs/images/pdfcoords.svg",
    "docs/make.bat",
    "docs/Makefile",
    "docs/requirements.txt",
    "tests/resources/1biticc.pdf",
    "tests/resources/aquamarine-cie.pdf",
    "tests/resources/aquamarine-cie.png",
    "tests/resources/cmyk-jpeg.pdf",
    "tests/resources/form.pdf",
    "tests/resources/formxobject.pdf",
    "tests/resources/fourpages.pdf",
    "tests/resources/image-mono-inline.pdf",
    "tests/resources/invalid_creationdate.pdf",
    "tests/resources/newline-buffer-test.pdf",
    "tests/resources/pal**.pdf",
    "tests/resources/pdfx.pdf",
    "tests/resources/pink-palette-icc.pdf",
    "tests/resources/pink-palette-icc.png",
    "tests/resources/rle.pdf",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2023 James R. Barlow"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "tests/resources/ccitt-endofline-true.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Leon Eckardt"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["docs/images/pike.png", "tests/resources/pike**jp2.pdf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Public domain"
SPDX-License-Identifier = "Public-domain"
SPDX-FileComment = "From the U.S. Fish and Wildlife Service National Image Library. See: https://en.wikipedia.org/wiki/File:Esox_lucius1.jpg"

[[annotations]]
path = "docs/images/pike-release.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2014 Azerty197666"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "Obtained from: https://commons.wikimedia.org/wiki/File:Release_of_a_pike.jpg"

[[annotations]]
path = "docs/images/pike-cartoon.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2017 creozavr"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "Obtained from: https://pixabay.com/en/pike-fish-predator-shchuchin-2612354/"

[[annotations]]
path = "docs/images/pikemen.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2009 Rama"
SPDX-License-Identifier = "CECILL-2.0"
SPDX-FileComment = "Obtained from: https://commons.wikimedia.org/wiki/File:Pike_square_img_3653.jpg"

[[annotations]]
path = "docs/images/save-pike.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2007 Sarah777"
SPDX-License-Identifier = "Public-domain"
SPDX-FileComment = "See: https://upload.wikimedia.org/wikipedia/commons/3/33/SaveDePike.jpg"

[[annotations]]
path = "docs/images/sushi.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2004 Gérald Anfossi"
SPDX-License-Identifier = "GFDL-1.2-or-later or CC-BY-SA-3.0"
SPDX-FileComment = "See: https://commons.wikimedia.org/wiki/File:Sushi_bento.jpg"

[[annotations]]
path = "docs/images/28fish.jpg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2014 Wellcome Library, London"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Obtained from https://commons.wikimedia.org/wiki/File:Twenty_eight_types_of_fish._Engraving_by_R._Scott_after_T._B_Wellcome_V0022737EL.jpg\n               https://wellcomecollection.org/works/hwzup9cj?wellcomeImagesUrl=/indexplus/image/V0022737EL.html Year of copyright given above is date of upload to Wikimedia Commons.\n This may not be when the scan/photograph was actually produced by the\n Wellcome Library.  The original work is from the 19th century."

[[annotations]]
path = "tests/resources/Gray.icc"
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "Kai-Uwe Behrmann <www.behrmann.name>",
    "Marti Maria <www.littlecms.com>",
    "Photogamut <www.photogamut.org>",
    "Graeme Gill <www.argyllcms.com>",
    "ColorSolutions <www.basICColor.com>",
]
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = [
    "tests/resources/congress.pdf",
    "docs/images/congress_im0.jpg",
    "tests/resources/congress-gray.pdf",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Public domain"
SPDX-License-Identifier = "Public-domain"
SPDX-FileComment = "From US Congressional Records. Converted from JPEG to PDF."

[[annotations]]
path = "tests/resources/content-stream-errors.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2019 Jay Berkenbilt"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "tests/resources/graph**.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Public domain"
SPDX-License-Identifier = "Public-domain"
SPDX-FileComment = "Released into the public domain by author; see: <https://en.wikipedia.org/wiki/File:Pandas_text_analysis.png>. For -encrypted.pdf, user password is \"user\" and owner password is \"owner\"."

[[annotations]]
path = "tests/resources/jbig2.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Public domain"
SPDX-License-Identifier = "Public-domain"

[[annotations]]
path = "tests/resources/jbig2global.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2005 Ellywa"
SPDX-License-Identifier = "GFDL-1.2-or-later or CC-BY-SA-1.0 or CC-BY-SA-2.0 or CC-BY-SA-2.5 or CC-BY-SA-3.0"
SPDX-FileComment = "Obtained from: https://commons.wikimedia.org/wiki/File:Triumph.typewriter_text_Linzensoep.gif\n Converted to PDF."

[[annotations]]
path = "tests/resources/outlines.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2020 Matthias Erll"
SPDX-License-Identifier = "MPL-2.0"
SPDX-FileComment = "License assumed from LICENSE.txt in project root."

[[annotations]]
path = "tests/resources/sandwich.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 1985 Forat Electronics"
SPDX-License-Identifier = "GFDL-1.2-or-later or CC-BY-SA-3.0"
SPDX-FileComment = "Created using ocrmypdf --pdf-renderer sandwich, to test Tesseract PDF\n text encoding. Originally obtained from: https://commons.wikimedia.org/wiki/File:LinnSequencer_hardware_MIDI_sequencer_brochure_page_2_300dpi.jpg"

[[annotations]]
path = "tests/resources/veraPDF**.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2015 veraPDF Consortium"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Obtained from: https://github.com/veraPDF/veraPDF-corpus"
