# SPDX-FileCopyrightText: 2026 James R. Barlow
# SPDX-License-Identifier: MPL-2.0

"""The veraPDF rule catalogue and our disposition of each rule.

``verapdf_rules.json`` is generated by ``misc/import_verapdf_profiles.py`` from
the veraPDF validation profiles (CC BY 4.0, veraPDF Consortium).
``dispositions.json`` records, for every rule, how this validator handles it.
"""

from __future__ import annotations

import json
from functools import cache
from importlib.resources import files
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from importlib.resources.abc import Traversable


def data_file(*parts: str) -> Traversable:
    """Return a file in the package ``data`` directory."""
    return files('pikepdf.pdfa').joinpath('data', *parts)


def load_json(*parts: str) -> Any:
    """Parse a JSON file in the package ``data`` directory."""
    return json.loads(data_file(*parts).read_text(encoding='utf-8'))


@cache
def _load(name: str) -> Any:
    return load_json(name)


def load_rules() -> dict[str, dict[str, str]]:
    """Return the veraPDF rules keyed by rule id (``ISO_19005_2:6.2.8-3``)."""
    return _load('verapdf_rules.json')['rules']


def load_dispositions() -> dict[str, dict[str, str]]:
    """Return our disposition of every veraPDF rule, keyed by rule id."""
    return {
        rule_id: disposition
        for rule_id, disposition in _load('dispositions.json').items()
        if not rule_id.startswith('$')
    }


def describe_rule(rule_id: str) -> str:
    """Return a one-line description of a rule, for log messages."""
    rule = load_rules().get(rule_id)
    if rule is None:
        return f"{rule_id}: unknown rule"
    return f"{rule_id}: {rule['description']}"
