// SPDX-FileCopyrightText: 2022 James R. Barlow
// SPDX-License-Identifier: MPL-2.0

#pragma once

#include "pikepdf.h"

#include <nanobind/trampoline.h>

#include <string>

#include <qpdf/QPDFTokenizer.hh>

// Used to implement pikepdf.StreamParser, which can be subclassed to implement
// custom parsing.
class PyParserCallbacks : public QPDFObjectHandle::ParserCallbacks {
public:
    NB_TRAMPOLINE(QPDFObjectHandle::ParserCallbacks, 2);
    virtual ~PyParserCallbacks() = default;

    void handleObject(QPDFObjectHandle obj, size_t offset, size_t length) override;
    void handleEOF() override;
};

class ContentStreamInstruction {
public:
    ContentStreamInstruction(ObjectList operands, QPDFObjectHandle operator_);
    virtual ~ContentStreamInstruction() = default;

    ObjectList operands;
    QPDFObjectHandle operator_;
};

class ContentStreamInlineImage {
public:
    ContentStreamInlineImage(ObjectList image_metadata,
        QPDFObjectHandle image_data,
        QPDFObjectHandle resources = QPDFObjectHandle())
        : image_metadata(image_metadata), image_data(image_data), resources(resources)
    {
    }
    virtual ~ContentStreamInlineImage() = default;

    ObjectList image_metadata;
    QPDFObjectHandle image_data;
    // The /Resources dictionary in scope, used to resolve named colour spaces
    // referenced by the inline image. Null when no resources are available.
    QPDFObjectHandle resources;

    py::list get_operands() const;
    QPDFObjectHandle get_operator() const;

    py::object get_inline_image() const;
};

// Groups the objects of a content stream into instructions: operands followed
// by their operator, or an inline image (BI ... ID data EI). Subclasses decide
// what to do with each complete instruction.
class InstructionGrouper : public QPDFObjectHandle::ParserCallbacks {
public:
    explicit InstructionGrouper(QPDFObjectHandle resources = QPDFObjectHandle())
        : resources(resources)
    {
    }
    void handleObject(QPDFObjectHandle obj) override;
    void handleEOF() override;

    std::string getWarning() const { return this->warning; }

protected:
    // Whether to keep instructions with this operator; the operands of a
    // rejected operator are discarded along with it
    virtual bool accepts(std::string const &op) const { return true; }
    virtual void handle_instruction(ObjectList &operands,
        QPDFObjectHandle const &operator_,
        std::string const &op) = 0;
    virtual void handle_inline_image(ContentStreamInlineImage csii) = 0;

private:
    ObjectList tokens;
    bool parsing_inline_image = false;
    ObjectList inline_metadata;
    std::string warning;
    // The /Resources in scope for this content stream, forwarded to inline
    // images so they can resolve named colour spaces. Null when unavailable.
    QPDFObjectHandle resources;
};

// Used for parse_content_stream. Collects every instruction, optionally only
// those whose operators are in a whitelist.
class OperandGrouper : public InstructionGrouper {
public:
    OperandGrouper(
        const std::string &operators, QPDFObjectHandle resources = QPDFObjectHandle());

    py::list getInstructions() const;

protected:
    bool accepts(std::string const &op) const override;
    void handle_instruction(ObjectList &operands,
        QPDFObjectHandle const &operator_,
        std::string const &op) override;
    void handle_inline_image(ContentStreamInlineImage csii) override;

private:
    std::set<std::string> whitelist;
    py::list instructions;
};

// Append the PDF serialization of one instruction to out
void append_unparsed(std::string &out, ContentStreamInstruction &csi);
void append_unparsed(std::string &out, ContentStreamInlineImage &csii);

// unparse the list of instructions generated by an OperandGrouper
py::bytes unparse_content_stream(py::iterable contentstream);
