// SPDX-FileCopyrightText: 2022 James R. Barlow
// SPDX-License-Identifier: MPL-2.0

#pragma once

#include "pikepdf.h"

#include <nanobind/trampoline.h>

#include <string>

#include <qpdf/QPDFTokenizer.hh>

// Used to implement pikepdf.StreamParser, which can be subclassed to implement
// custom parsing.
class PyParserCallbacks : public QPDFObjectHandle::ParserCallbacks {
public:
    NB_TRAMPOLINE(QPDFObjectHandle::ParserCallbacks, 2);
    virtual ~PyParserCallbacks() = default;

    void handleObject(QPDFObjectHandle obj, size_t offset, size_t length) override;
    void handleEOF() override;
};

class ContentStreamInstruction {
public:
    ContentStreamInstruction(ObjectList operands, QPDFObjectHandle operator_);
    virtual ~ContentStreamInstruction() = default;

    ObjectList operands;
    QPDFObjectHandle operator_;
};

class ContentStreamInlineImage {
public:
    ContentStreamInlineImage(ObjectList image_metadata,
        QPDFObjectHandle image_data,
        QPDFObjectHandle resources = QPDFObjectHandle())
        : image_metadata(image_metadata), image_data(image_data), resources(resources)
    {
    }
    virtual ~ContentStreamInlineImage() = default;

    ObjectList image_metadata;
    QPDFObjectHandle image_data;
    // The /Resources dictionary in scope, used to resolve named colour spaces
    // referenced by the inline image. Null when no resources are available.
    QPDFObjectHandle resources;

    py::list get_operands() const;
    QPDFObjectHandle get_operator() const;

    py::object get_inline_image() const;
};

// Used for parse_content_stream. Handles each object by grouping into operands
// and operators. The whole parse stream can be retrieved at once.
class OperandGrouper : public QPDFObjectHandle::ParserCallbacks {
public:
    OperandGrouper(
        const std::string &operators, QPDFObjectHandle resources = QPDFObjectHandle());
    void handleObject(QPDFObjectHandle obj) override;
    void handleEOF() override;

    py::list getInstructions() const;
    std::string getWarning() const;

private:
    std::set<std::string> whitelist;
    std::vector<QPDFObjectHandle> tokens;
    bool parsing_inline_image;
    std::vector<QPDFObjectHandle> inline_metadata;
    py::list instructions;
    uint count;
    std::string warning;
    // The /Resources in scope for this content stream, forwarded to inline
    // images so they can resolve named colour spaces. Null when unavailable.
    QPDFObjectHandle resources;
};

// Append the PDF serialization of one instruction to out
void append_unparsed(std::string &out, ContentStreamInstruction &csi);
void append_unparsed(std::string &out, ContentStreamInlineImage &csii);

// unparse the list of instructions generated by an OperandGrouper
py::bytes unparse_content_stream(py::iterable contentstream);
